name: Go React CRUD CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Go Lint
        uses: golangci/golangci-lint-action@v8
        with:
          working_directory: backend
        
      - name: Build docker images for frontend, backend and postgres & Start Go React CRUD Application
        run: docker compose up --build -d
        
      - name: Check containers
        run: docker compose ps 

      - name: Check backend logs
        run: docker compose logs backend
        
      - name: Check frontend logs
        run: docker compose logs frontend

      - name: Test GET users
        run: curl --fail http://localhost:3000/api/users

      - name: Test CREATE user
        run: | 
          curl --fail -X POST http://localhost:3000/api/users -H "Content-Type: application/json" -d '{"name":"CI Test User"}'

      - name: Test DELETE user
        run: curl --fail -X DELETE http://localhost:3000/api/users/1
        
      - name: Test frontend proxy
        run: curl --fail http://localhost:3000/api/users
