name: Go React CRUD CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker images for frontend, backend and postgres
        run: docker compose build
    
      - name: Start Go React CRUD Application
        run: docker compose up -d
  
      - name: Check containers
        run: docker compose ps 
      
      - name: Test frontend
        run: curl --fail http://localhost:3000

      - name: Test backend
        run: curl --fail http://localhost:8000
